[project]
name = "personality-forge"
version = "0.1.0"
description = "a personality generator for AIs"
readme = "README.md"
authors = [
    { name = "znovo", email = "znovo123new@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.141.1",
    "openai>=3.16.2",
    "python-dotenv>=1.2.3",
    "uvicorn>=0.53.0",
]

[project.scripts]
personality-forge = "personality_forge:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
